### PR TITLE
Fix some grammatical problems

### PR DESCRIPTION
**Pull request by GoodLucky777**

### CODE REVIEW

**Comment by lt-name** [comment]
I try to use Google translation examination,
But these translations do not seem to be as good as the original translation
So I will wait for others to express their opinions

**Comment by GoodLucky777** [comment]
Because google translate sometimes doesn't work very well. Also Korean have lot of expression for one word. I recommend to use Papago translator if you are translating between Korean and Chinese. It is more better than Google Translate when you are translating Korean.

**Comment by GoodLucky777** [comment]
Also I change `로드` to `불러오기` because it is more better expression.

**Review by lt-name — APPROVED** [review]

**Comment by deveworld** [comment]
Ok. I accept about 불러오기, too.

**Pull request merged**
